fragment SongDataFragment on AlbumData {
  songs {
    sid
    artist {
      id
      altName
      artistImage
      shareToken
    }
    genres
    feats {
      name
      position
    }
    title
    subtitle
    explicit
    duration
    songUrl
    songImage
  }
}